package licos.protocol.element.village.server2client.server2logger

import licos.protocol.element.village.{Server2Logger, VillageMessageProtocol}

trait Server2ClientVillageMessageProtocolForLogging extends VillageMessageProtocol with Server2Logger
