package licos.protocol.element.village.client2server.server2logger

import licos.protocol.element.village.{Server2Logger, VillageMessageProtocol}

trait Client2ServerVillageMessageProtocolForLogging extends VillageMessageProtocol with Server2Logger
