package licos.json.engine.analysis.village.client2server

import licos.json.engine.analysis.village.MetaAnonymousAudienceChatAnalysisEngine

trait AnonymousAudienceChatAnalysisEngine extends MetaAnonymousAudienceChatAnalysisEngine
