package licos.json.engine.analysis.village.client2server

import licos.json.engine.analysis.village.MetaAudienceChatAnalysisEngine

trait AudienceChatAnalysisEngine extends MetaAudienceChatAnalysisEngine
