package licos.json.engine.analysis.village.client2server

import licos.json.engine.analysis.village.MetaOnymousAudienceChatAnalysisEngine

trait OnymousAudienceChatAnalysisEngine extends MetaOnymousAudienceChatAnalysisEngine
