package licos.json.engine.analysis.village.server2client

import licos.json.engine.analysis.village.MetaAnonymousAudienceChatAnalysisEngine

trait AnonymousAudienceChatAnalysisEngine extends MetaAnonymousAudienceChatAnalysisEngine
