package licos.json.engine.analysis.village.server2client

import licos.json.engine.analysis.village.MetaAudienceChatAnalysisEngine

trait AudienceChatAnalysisEngine extends MetaAudienceChatAnalysisEngine